assingment 1
vmishragreprubycom/assignment_work pull request #1
Opened 2017-06-14 14:02 UTC by vmishragreprubycom

2017-06-14 14:13 UTC, rockon1985 requested changes
make mentioned code changes

2017-06-14 14:13 UTC, ketanTechracers commented on assignment1/day 2/calculateFrequency.js
> +  var a=Array.from(string);
what is `a` ? Give the variable some relevant name

2017-06-14 14:13 UTC, ketanTechracers commented on assignment1/day 2/calculateFrequency.js
> +  var output=[];
there should be a space before and after the operator in JS code. eg: `a + b` instead of `a+b`

2017-06-14 14:13 UTC, ketanTechracers commented on assignment1/day 2/calculateFrequency.js
> +                 output[a[i]]++;
instead of assigning it 0 and then incrementing, directly initialise it by 1.

2017-06-14 14:13 UTC, ketanTechracers commented on assignment1/day 2/calculateFrequency.js
> +       }
correct indentation in this file. Required indentation should be 2 spaces.

2017-06-14 14:13 UTC, ketanTechracers commented on assignment1/day 2/flatten.js
> +  {
correct indentation! code is very unreadable this way!

2017-06-14 14:13 UTC, ketanTechracers commented on assignment1/day 2/secondLargest.js
> +  var second_highest=max;
variable names should be _camelCased_ and not _underscore_separated_

2017-06-14 14:13 UTC, ketanTechracers commented on assignment1/day 2/unflatten.js
> +    //alert(key.split('.'));
remove commented code

2017-06-14 14:46 UTC, rockon1985 requested changes

2017-06-14 14:46 UTC, ketanTechracers commented on assignment1/day 2/calculateFrequency.js
> +    //console.log(array);
remove commented code and comments which are not necessary.

2017-06-14 14:46 UTC, ketanTechracers commented on assignment1/day 2/calculateFrequency.js
> +        if (array[i].charCodeAt(0) > 96 && array[i].charCodeAt(0) < 123) {
correct indentation again!

2017-06-14 14:46 UTC, ketanTechracers commented on assignment1/day 2/secondLargest.js
> +    var second_highest = max;
dont use underscore_separated variable names

2017-06-14 14:46 UTC, ketanTechracers commented on assignment1/day 2/unflatten.js
> +        //alert(key.split('.'));
remove commented code!

2017-06-14 14:46 UTC, ketanTechracers commented on assignment1/day 2/unflatten.js
> +}
file should end with a new line character.

2017-06-14 15:27 UTC, rockon1985 approved these changes

2017-06-15 11:02 UTC, devanshutechracers commented on assignment1/day 2/calculateFrequency.js
> +  var array = Array.from(string);
Do you really need to convert the string to array.

2017-06-15 11:03 UTC, devanshutechracers requested changes
Small Change Required.

2017-06-15 13:36 UTC, devanshutechracers commented on assignment1/day 2/secondLargest.js
> +function calculateFrequency(string) {
Wrong code in secondLargest.js
Review your changes before commit

2017-06-15 13:36 UTC, devanshutechracers commented on assignment1/day 2/calculateFrequency.js
> +  var array = Array.from(string);
still not correct

2017-06-15 13:37 UTC, devanshutechracers requested changes
Misplaced files. Self Review is important before submission.

2017-06-16 13:55 UTC, devanshutechracers approved these changes

2017-06-16 14:01 UTC, merged

2017-06-20 12:17 UTC, devanshutechracers commented on assignment1/day 2/calculateFrequency.js
> +    var currentCharacter=string.charAt(i);
space around `=` operator